services:
  - type: web
    name: app
    env: docker
    repo: https://github.com/rohan11061/ollama-streamlit-app
    region: oregon
    plan: starter
    branch: master
    healthCheckPath: /
    autoDeploy: true
